on:
  push: {}

jobs:
  build:
    name: Build binary
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos:
          - linux
          - darwin
        goarch:
          - amd64
          - arm64
          - arm
        include:
          - goos: linux
            goarch: arm
            goarm: 7
        exclude:
          - goos: darwin
            goarch: arm

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Build binaries
        run: make
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          GOARM: ${{ matrix.goarm }}
      - uses: actions/upload-artifact@v2
        with:
          name: oaitool-${{ matrix.goos }}-${{ matrix.goarch }}
          path: oaitool-${{ matrix.goos }}-${{ matrix.goarch }}
